### ISSUE TITLE
Symbol's value as variable is void: lsp-language-id-configuration.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#47] opened 2021-05-25 07:04 UTC
On Ubuntu 20.04, I try to use `lsp-wl` in the self compiled git master version of Emacs using the following settings in `~/.emacs.d/init.el` according to the notes [here](https://github.com/kenkangxgwe/lsp-wl/wiki#gnu-emacs):

```
(add-to-list 'lsp-language-id-configuration '(wolfram-mode . "Mathematica"))

(lsp-register-client
 (make-lsp-client :language-id 'wolfram
                  :new-connection (lsp-tcp-server-command
                                   (lambda (port)
                                     `("wolfram" ;; or "wolframscript"
                                       "-script" ;; or "-file"
                                       "~/Public/repo/github.com/kenkangxgwe/lsp-wl.git/init.wls"
                                       ,(concat
                                         "--socket="
                                         (number-to-string port)
                                         ))))
                  :major-modes '(wolfram-mode)
                  :server-id 'lsp-wl
                  ))
```

But when I start Emacs, I noticed the following info:

```
Warning (initialization): An error occurred while loading ‘/home/werner/.emacs.d/init.el’:

Symbol's value as variable is void: lsp-language-id-configuration
```
Any hints for fixing this problem?

Regards,
HY

**Comment by kenkangxgwe** [comment] 2021-05-26 03:59
Duplicate of #48

**Closed as completed by kenkangxgwe** 2021-05-26 03:59 UTC
