### ISSUE TITLE
Mathematica 12.1 stop working after installing these Paclets....

### ISSUE THREAD

**Issue by hhchi13** [kenkangxgwe/lsp-wl#32] opened 2020-09-06 05:38 UTC
Hi,
I played with this language server protocol yesterday and following instructions, I ran PacletInstall["CodeParser"]
PacletInstall["CodeInspector"] in my Mathematica 12.1 notebook.

However, my MMA stopped working today. It freezes at the initializing process when I try to open it.

Any advice on undo the language server protocol and these 2 installed paclets, so I can make MMA work again?

PS: I tried to reinstall MMA, but it still doesn't work.
![image](https://user-images.githubusercontent.com/50938783/92318981-8ff37a80-efe1-11ea-8c2c-525ea14cff29.png)

**Comment by kenkangxgwe** [comment] 2020-09-06 06:12
Hi @hhchi13 , I doubt that this is related to the language server or the two paclets it depends on, because none of them will be loaded automatically when Mathematica starts up. But to debug the problem, please try to open the `wolfram` executable under your installation directory and run
``` mathematica
PacletUninstall["CodeParser"]
PacletUninstall["CodeInspector"]
```
![image](https://user-images.githubusercontent.com/8650023/92319448-1487ce00-efcd-11ea-8f1f-c53241880d6b.png)

Or you can try to delete two paclet folders under `$HOME/Mathematica/Paclets/Repository`. For example, on Windows, it lies under `%APPDATA%\Mathematica\Paclets\Repository`.

![image](https://user-images.githubusercontent.com/8650023/92319430-e99d7a00-efcc-11ea-9456-05e31e6de461.png)

**Comment by hhchi13** [comment] 2020-09-06 06:35
Hi @kenkangxgwe , thanks for the reply. 
I re-installed MMA, run the wolfram.exe, and find that these 2 parlets don't exist anymore. So I guess it is not parlets that freeze MMA. I'll dig more into this and try to figure out some solution.

**Comment by kenkangxgwe** [comment] 2020-09-07 03:10
Hi, Assuming this is resolved or confirmed not related to the language server, I am closing it. Thanks for your feedback.

**Closed by kenkangxgwe** 2020-09-07 03:10 UTC
Labels: dependency
