### ISSUE TITLE
No output on debug console with `Print`, but `Echo` doesn't have this problem.

### ISSUE THREAD

**Issue by hongyi-zhao** [kenkangxgwe/lsp-wl#56] opened 2021-05-29 00:56 UTC
Evaluate in debug console within `vscode` via `lsp-wl`:

![image](https://user-images.githubusercontent.com/11155854/120054087-6ba06800-c060-11eb-943b-a775137435bb.png)

In MMA notebook:

![image](https://user-images.githubusercontent.com/11155854/120054063-51ff2080-c060-11eb-8579-7014f522fac1.png)

Why?

Regards,
HY

**Comment by kenkangxgwe** [comment] 2021-05-29 02:07
The same issue as #57 , it is unknown to me how to redirect stdout from another kernel. You should see it printed in the log panel.

**Comment by kenkangxgwe** [comment] 2021-05-30 08:27
Duplicate of #57

**Closed as completed by kenkangxgwe** 2021-05-30 08:27 UTC
Labels: enhancement
